### ISSUE TITLE
CherryPy

### ISSUE THREAD

**Issue by erasche** [erasche/galaxy-data_source-examples#1]
Pinging @TorHou I didn't know you put together the [cherry py](https://gist.github.com/TorHou/b4ee6890442c5c3d479d) stuff.

Obviously, this repo has a flask app that serves up both types of Galaxy data sources, and I have a [django](https://github.com/erasche/django-galaxydatasource) version as well.

Would be interested in merging all of this, if you'd like. :)

cc @bgruening

**Comment by TorHou** [comment]
sure go ahead. I didn't know about this repo, I saw that you were working on this somewhere ... 

We should update the wiki as well.

**Comment by erasche** [comment]
Sounds good! I'll pull your stuff in, and my django stuff, and soon we'll have examples for all the python systems. Great work with CherryPy :)

**Comment by TorHou** [comment]
cheers :beer:

**Comment by bgruening** [comment]
Awesome!
