### ISSUE TITLE
How to install sync.xml into the Galaxy toolbox

### ISSUE THREAD

**Issue by twhetzel** [erasche/galaxy-data_source-examples#2]
In the docs it mentions to "Install sync.xml into your Galaxy toolbox". Do you have details on how to do this step?

**Comment by erasche** [comment]
Without double checking, this usually means "add the path to the sync.xml to `$GALAXY_ROOT/config/tool_conf.xml`"

**Comment by twhetzel** [comment]
Thanks, that worked!
